### ISSUE TITLE
Uptime / status page not working

### ISSUE THREAD

**Issue by ajdor** [simple-login/uptime#12]
Uptime URL linked in the readme is not working and is not redirecting or set as an alias to https://simple-login.github.io/uptime/

The old URL that was used with the previous uptime monitoring service is not working https://status.simplelogin.io/.
It returns an SSL error code: SSL_ERROR_NO_CYPHER_OVERLAP.
I think that URL should also redirect to https://simple-login.github.io/uptime/ since it's where users would expect to find uptime info.

Tested on Firefox 89.0

**Comment by nguyenkims** [comment]
@ajdor this is indeed a bug! We have fixed it by removing uptimerobot from the README.
